### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by iamwithnail** [loftylabs/djdevpanel-devtools#3]
When I go to Load the unpacked extension, I get: 

Failed to load extension from: ~/Library/Application Support/Google/Chrome/Default/Extensions/joeiapdjinonjadfbdabogjimfffpfph/0.1.1_0
Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.

{
   "author": "Lofty Labs",
   "background": {
      "page": "background.html"
   },
   "content_security_policy": "script-src 'self' https://www.google-analytics.com; object-src 'self'",
   "description": "Debugging tools for Django applications.",
   "devtools_page": "devtools.html",
   "homepage_url": "https://github.com/loftylabs/django-developer-panel",
   "icons": {
      "128": "icon128.png"
   },
   "key": "keyherenotsureifitssensitive",
   "manifest_version": 2,
   "name": "Django Developer Panel",
   "permissions": [ "tabs", "http://*/*", "https://*/*" ],
   "short_name": "djdevpanel",
   "update_url": "https://clients2.google.com/service/update2/crx",
   "version": "0.1.1"
}

Mac OSX 10.12.24
Chrome  57.0.2987.133 (64-bit)

This is pointing the load file at the 0.1.1_0 file inside the relevant extension folder - should it be pointing somewhere else?

**Comment by ckinsey** [comment]
Hello @iamwithnail,  when you load an unpacked extension you just point it at the containing folder.  For example, if you were to clone this repository with the default name (`git clone git@github.com/loftylabs/djdevpanel-devtools.git`) you would point at the `djdevpanel-devtools` directory.

If you're not planning on doing active development though, you should just install the extension via the Chrome Web Store and it will appear in your developer tools--no unpacking/developer mode required.
